// <auto-generated />
namespace Session6Instagram.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class UsersAndPhotos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UsersAndPhotos));
        
        string IMigrationMetadata.Id
        {
            get { return "201807182232106_UsersAndPhotos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
